language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - pip install git+https://github.com/sopel-irc/sopel.git
install: pip install -e .
script:
  - pycodestyle --show-source --ignore=E501,E402,E722  ./
  - coverage run -m py.test -v .
  - coverage report
after_success:
  - coveralls
deploy:
  provider: pypi
  user: rustybower
  password:
    secure: qi2g9+gRHop88zHwkLcXnIt51LCIGW/Md2yOFQqAfBsMLGwYayC8da6Y9UeOhcf5fh9ULEyZTIjoiQXNpZAQCRQa6JNLKKNGk8cWgwf5DemARrxKB8QKn9ytBgvwWTtHZrvavPcOJhHLUiaY935G6YWiBaRm+OQsIOgbZmDpzePqPmkGpQ8r0jOGea1rXwdqP30HL4hKxA+GvH/dkvwX8bwR5pvU18S5Dww4WjOi5VUbgAzEowosGHKGJ7q02QLb2PdH/Ad1cdzra2a6K6cU9Spd6G8zAznrMiqZJmayl3njCZCXYojdEu2wuXlxLtNz9jlBpXAp3VQ7n845nmDoCFe3n+D/fERpE/n7qiO0zmabNOhTgSHB6oGiguRsJcZoGbzKCX25lNBDqk55okwwJY7UArV1Rcb0v4A82HS+/DnvojkiYvCryI7dkzm0+z1t6YgQQAdzk+/hc9tArGCMjtyJ1/Evgen2Ak6sGiaN8EFTN5wipPE9cCCsI6/OUv90x8PIlTa3F+f+csaoKWDRDWj2+3t6Z3cfWiwg3bJTfz2KiUzjAwEMJo7Ln/zokN9N+8PAakiKz913cfcJ0TCg8fgf2dsIQltZAwm2BidUs8hFNgEGvf/l/VZC0+PhqjYHAnWih7riaNOiHhA1Bgr09YrhZPbIjGmiP6vT+2Y0y4E=
  on:
    tags: true
    python: '3.5'
  skip_existing: true
